const buildInvoiceEmail = ({
  contract,
  property,
  client,
  reports,
  subTasks,
  invoice
}) => {
  const BASE_URL = process.env.BACKEND_URL?.replace(/\/$/, "");

  // 🔥 map subtask
  const subTaskMap = {};
  subTasks.forEach(s => {
    subTaskMap[s._id.toString()] = s;
  });

  // ================= SERVICE TABLE =================
  const serviceRows = reports.map(r =>
    r.completedSubTasks.map(s => `
      <tr>
        <td style="padding:10px;border:1px solid #ddd;">${s.name}</td>
        <td style="padding:10px;border:1px solid #ddd;">
          ${(s.timeSeconds / 3600).toFixed(2)} hrs
        </td>
        <td style="padding:10px;border:1px solid #ddd;">₹${s.price || 0}</td>
      </tr>
    `).join("")
  ).join("");

  // ================= TOTAL HOURS =================
  const totalHours = reports.reduce(
    (sum, r) => sum + (r.totalHours || 0),
    0
  );

  // ================= IMAGE FIX (IMPORTANT) =================
  const getFullUrl = (url) =>
    `${BASE_URL}/${url.replace(/^\/+/, "")}`;

  const beforeImages = reports.flatMap(r =>
    r.completedSubTasks.flatMap(s => {
      const full = subTaskMap[s.subTaskId.toString()];
      return (full?.beforeWorkImages || []).map(img => `
        <img 
          src="${getFullUrl(img.url)}"
          width="140"
          style="display:inline-block;margin:5px;border-radius:6px;"
        />
      `);
    })
  ).join("");

  const afterImages = reports.flatMap(r =>
    r.completedSubTasks.flatMap(s => {
      const full = subTaskMap[s.subTaskId.toString()];
      return (full?.afterWorkImages || []).map(img => `
        <img 
          src="${getFullUrl(img.url)}"
          width="140"
          style="display:inline-block;margin:5px;border-radius:6px;"
        />
      `);
    })
  ).join("");

  // ================= INVOICE DATA =================
  const totalAmount = invoice?.amount || 0;
  const invoiceNumber = invoice?.invoiceNumber || invoice?._id?.toString().slice(-6);

  const dueDate = invoice?.dueDate || new Date(invoice.createdAt);
  dueDate.setDate(dueDate.getDate() + 7);

  // ================= HTML =================
  return `
  <div style="font-family:Arial;background:#f4f6f9;padding:20px;">
    <div style="max-width:800px;margin:auto;background:#fff;padding:25px;border-radius:10px;">

      <h2 style="color:#2c3e50;">Invoice & Work Report</h2>

      <p><b>Invoice No:</b> ${invoiceNumber}</p>
      <p><b>Billing Type:</b> ${contract.billingType}</p>
      <p><b>Due Date:</b> ${dueDate.toDateString()}</p>

      <hr/>

      <h3>📄 Contract Details</h3>
      <p><b>Contract No:</b> ${contract.contractNumber}</p>
      <p><b>Start:</b> ${new Date(contract.startDate).toDateString()}</p>
      <p><b>End:</b> ${new Date(contract.endDate).toDateString()}</p>

      <h3>👤 Client</h3>
      <p>${client.name} (${client.email})</p>

      <h3>🏢 Property</h3>
      <p>${property.propertyName}</p>
      <p>${property.location?.address || ""}</p>

      <h3>🧾 Services</h3>
      <table style="width:100%;border-collapse:collapse;">
        <tr style="background:#f1f1f1;">
          <th style="padding:10px;border:1px solid #ddd;">Service</th>
          <th style="padding:10px;border:1px solid #ddd;">Time</th>
          <th style="padding:10px;border:1px solid #ddd;">Price</th>
        </tr>
        ${serviceRows}
      </table>

      ${contract.billingType === "hourly"
      ? `
        <h3 style="margin-top:20px;">⏱ Hourly Breakdown</h3>
        <p><b>Total Hours:</b> ${totalHours.toFixed(2)} hrs</p>
        <p><b>Rate:</b> ₹${contract.hourlyRate}/hr</p>
      `
      : ""
    }

      <h3 style="margin-top:20px;">📸 Before Work</h3>
      <div>${beforeImages || "No images available"}</div>

      <h3 style="margin-top:20px;">📸 After Work</h3>
      <div>${afterImages || "No images available"}</div>

      <hr/>

      <h2 style="text-align:right;color:#27ae60;">
        Total Amount: ₹${totalAmount.toFixed(2)}
      </h2>

      <p style="margin-top:20px;">
        Please proceed with payment before due date.
      </p>

      <p style="font-size:12px;color:#888;">
        This is an automated invoice generated by the system.
      </p>

    </div>
  </div>
  `;
};

module.exports = buildInvoiceEmail;